os: osx

jobs:
  include:
    osx_image:
    # OS X 10.15
      - xcode12
    script:
      - travis_wait 30 bats test/splinter-basics.bats
      - travis_wait 30 bats test/splinter-update.bats
      - ./splinter -q update tools
      - travis_wait 30 bats test/splinter-export.bats
      - travis_wait 120 bats test/splinter-create.bats
      - travis_wait 30 bats test/splinter-provision.bats

osx_image:
# OS X 10.15
  - xcode12
# OS X 10.14
  - xcode11.2

language: bash

env:
  - ANSIBLE_BECOME_PASS="travis"
install:
  # - brew update
  - brew install bats-core mas
  - pip install ansible-lint

script:
  - ansible-lint ./ansible/playbook.yml
  - ./splinter --verbose provision -u newuser -f 'NewUser'
