---
verbose: no
setup_profile_base: example-default
setup_profile: example # leave empty to use only the `default` profile settings
                    # custom profiles can be created inside the './profiles' directory
computer_name: ASSET-123
create_new_user: yes    # 'yes' or 'no'
new_user_username: 'developer' # leave empty '' to prevent the new user to be created
new_user_fullname: 'New Developer'
new_user_password_cleartext: 'password'
target_user_id: "{{ new_user_username }}" # The user we will configure

# DO NOT ADD MORE OPTIONS HERE
# ANY OTHER OPTION IN THIS FILE WILL BE OVERRIDDEN
# BY THE PROFILE SETTINGS IN the `./profiles/*` directories
