---

verbose: no
base_profile: "default"
# this is the profile to be used as base of all your profiles.
# Phe project already includes one default profile set that you can customise
# you can rename and copy the default profiel and have multiple different `default` profiles

role_profile: "example"
# You can leave thos `empty` to use only the `default` profile settings.
# Custom setup profiles can be created inside the './profiles' directory
# You can have many different profile to override specific settings of the `default` profile

create_new_user: yes # yes or no
new_user_username: "testuser"
# name of the new user to be created if you want to create one
# will be ignored if `create_new_user` is set to `no`

new_user_fullname: "Test User"
# full name of the new user
# will be ignored if `create_new_user` is set to `no`

new_user_password_cleartext: "password"
# will be ignored if `create_new_user` is set to `no`

target_user_id: "testuser"
# The user to which the configuration will be applied
# if commented or left `empty` the target user will be the (current) user that is running the provisioning

computer_name: "Test Computer"
# DO NOT ADD MORE OPTIONS HERE
# ANY OTHER OPTION IN THIS FILE WILL BE OVERRIDDEN
# BY THE PROFILE SETTINGS IN the `./profiles/*` directories
