---
- hosts: localhost
  connection: local
  vars:
    splinter_dir: "{{ lookup('env','SPLINTER_CONFIG_DIR') if lookup('env','SPLINTER_CONFIG_DIR')| length > 0 else playbook_dir + '/..' }}"

  vars_files:
    # Will load ONLY the fist avalilable item of the below list
    - [
        "{{ lookup('env','CUSTOM_CONFIG_FILE') if lookup('env','CUSTOM_CONFIG_FILE')|length > 0 else omit }}",
        "{{ splinter_dir + '/config.yml' }}",
        '/dev/null'
      ]

    - name: Load ENV and Default Values
      include_tasks: load-env-values.yml

    - name: Load the Splinter base tasks
      include_tasks: load-profiles.yml

  roles:
    - role: ctorgalson.macos_hostname
      when: configure_system|bool
      tags: ['osx']
      ignore_errors: yes

    - role: marcomc.sophos-endpoint
      when: configure_sophos_endpoint|bool
      tags: ['non_mas']
      ignore_errors: yes

    - role: marcomc.macos-new-user
      when: create_new_user|bool
      tags: ['new-user']
      ignore_errors: yes

    - role: marcomc.user-ssh-config
      when: create_new_user|bool
      tags: ['new-user']
      ignore_errors: yes

    - role: marcomc.filevault2
      when: configure_filevault|bool
      tags: ['osx']
      ignore_errors: yes

    - role: marcomc.homebrew-multi-user
      when: configure_homebrew|bool
      tags: ['homebrew']
      ignore_errors: yes
      # this position assumes/rquires that Homebrew is already installed by the splinter script

    - role: geerlingguy.homebrew
      when: configure_homebrew|bool
      tags: ['homebrew']
      ignore_errors: yes

    - role: marcomc.homebrew-autoupdate
      when: configure_homebrew|bool
      tags: ['homebrew']
      ignore_errors: yes

    - role: marcomc.splinter-extra-packages
      when: configure_extra_packages|bool
      tags: ['extra-packages']
      ignore_errors: yes

    - role: lafarer.osx-defaults
      when: configure_system|bool
      tags: ['osx']
      ignore_errors: yes

    - role: marcomc.macprefs-restore
      when: restore_dotfiles_with_macprefs|bool
      tags: ['dotfiles']
      ignore_errors: yes

    - role: marcomc.mackup
      when: restore_dotfiles_with_mackup|bool
      tags: ['dotfiles']
      ignore_errors: yes

    - role: geerlingguy.dotfiles
      when: configure_dotfiles|bool
      tags: ['dotfiles']
      ignore_errors: yes
      become: "{{ target_user_id != ansible_user_id }}"
      become_user: "{{ target_user_id }}"

    - role: juju4.macos_apps_install
      when: install_macos_apps|bool
      tags: ['non_mas']
      ignore_errors: yes
      environments:
        PATH: "{{ gnubin_path }}:{{ ansible_env.PATH }}"

    - role: marcomc.setapp
      when: configure_setapp|bool
      ignore_errors: yes

    - role: geerlingguy.mas
      when: install_mas_apps|bool
      tags: ['mas']
      ignore_errors: yes

  tasks:
    - name: Load the Splinter post provision tasks.
      include_role:
        name: marcomc.splinter-toolkit
        tasks_from: post-provision
      tags: ['always']

    - name: Run custom post-provision tasks.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
